apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    uid: microservices-es
    url: http://elasticsearch:9200
    access: proxy
    isDefault: true
    jsonData:
      index: "microservices-logs-*"
      timeField: "@timestamp"
      esVersion: "8.0.0"
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5
    version: 1
    editable: false
