apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
        - name: app
          image: nginx:1.25
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: # TODO: reference "db-secret"
                  key: # TODO: key "DB_USER"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: # TODO: reference "db-secret"
                  key: # TODO: key "DB_PASSWORD"
