apiVersion: v1
kind: Secret
metadata:
  name: # TODO: name it "db-secret"
type: Opaque
data:
  DB_USER: # TODO: base64 of "admin"     → echo -n "admin" | base64
  DB_PASSWORD: # TODO: base64 of "s3cur3pass" → echo -n "s3cur3pass" | base64
