apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-library.fullname" . }}
  labels:
    {{- include "my-library.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      containers:
        - name: app
          image: nginx:alpine
