apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace.name }}-quota
  namespace: {{ .Values.namespace.name }}
spec:
  hard:
    requests.cpu: {{ index .Values.namespaceQuotas "requests.cpu" | quote }}
    requests.memory: {{ index .Values.namespaceQuotas "requests.memory" | quote }}
    limits.cpu: {{ index .Values.namespaceQuotas "limits.cpu" | quote }}
    limits.memory: {{ index .Values.namespaceQuotas "limits.memory" | quote }}
