apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "nodejs.labels" . | nindent 4 }}
data:
  # TODO: Expose all keys from .Values.config as ConfigMap data
  # Hint: use range or toYaml | nindent
  NODE_ENV: ???
  PORT: ???
  LOG_LEVEL: ???
