events {}

http {
    upstream app {
        # TODO: Point to the blue service (blue:3000)
        # server ...;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://app;
        }
    }
}
