apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: observed-cluster
  namespace: config-connector
  annotations:
    cnrm.cloud.google.com/project-id: abiding-splicer-494411-m9
spec:
  location: us-central1-a
  initialNodeCount: 2
  loggingConfig:
    enableComponents:
      - SYSTEM_COMPONENTS
      - WORKLOADS
  monitoringConfig:
    enableComponents:
      - SYSTEM_COMPONENTS
      - APISERVER