apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: GREETING
              value: {{ .Values.config.greeting | quote }}
            - name: MAX_CONNECTIONS
              value: {{ .Values.config.maxConnections | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
