apiVersion: apps/v1
kind: Deployment
metadata:
  {{- /* TODO 3: Use include to render the fullname template */}}
  name: {{ include "???.fullname" . }}
  labels:
    {{- /* TODO 4: Use include to render the labels template, indented 4 spaces */}}
    {{- include "???.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        {{- include "named-templates.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
