apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
type: Opaque
stringData:
  # TODO: Add postgres-password key from .Values.auth.postgresPassword
  # Use required to enforce it is set
  postgres-password: ???
  # TODO: Add password key from .Values.auth.password
  password: ???
