apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-app
  template:
    metadata:
      labels:
        app: storage-app
    spec:
      containers:
        - name: app
          image: nginx:1.25
          volumeMounts:
            - name: data-vol
              mountPath: # TODO: mount at "/data"
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: # TODO: reference "local-pvc"
