apiVersion: v1
kind: ServiceAccount
metadata:
  name: sv-dv-9999-ksa-com1-0000
  namespace: app-dv-9999-default
  labels:
    environment: dev
    app: com1-0000
  annotations:
    iam.gke.io/gcp-service-account: sv-dv-9999-gsa-com1-0000@prj-dv-gitops-kata-1737.iam.gserviceaccount.com
