apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: app-9999-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: main
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/bin/hello-world.sh
          name: hello-world-config-map-volume
          readOnly: true
          subPath: hello-world.sh
        - mountPath: /app/conf/
          name: hello-world-secret-volume
          readOnly: true
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - /usr/local/bin/hello-world.sh
      volumes:
      - name: hello-world-config-map-volume
        configMap:
          name: hello-world-config-map
          defaultMode: 0555
      - name: hello-world-secret-volume
        secret:
          secretName: hello-world-secret
          defaultMode: 0444
