apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.dbSecretName }}
                  key: db-password

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.apiSecretName }}
                  key: api-key

            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.dbSecretName }}
                  key: db-host
                  optional: true
