apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: app-9999-default
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: main
        image: nginx:1.25
        resources:
          requests:
            cpu: "250m"
