apiVersion: v1
kind: Pod
metadata:
  name: mysqldbpod
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      ports:
        - name: mysqlport
          containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqldbsecret
              key: password
      volumeMounts:
        - name: mysqlvolume
          mountPath: /var/lib/mysql

  volumes:
    - name: mysqlvolume
      persistentVolumeClaim:
        claimName: mysqlpvc