apiVersion: v1
kind: Pod
metadata:
  name: coronapod
  labels:
    appName: corona
    version: "1.0"

spec:
  containers:
    - name: corona
      image: corona:1.0

      ports:
        - name: coronaport
          containerPort: 8080
          protocol: TCP

      env:
        - name: guidelines.oxygenLevels
          valueFrom:
            configMapKeyRef:
              name: guidelinesconfigmap
              key: oxygenLevels

        - name: guidelines.quarantine
          valueFrom:
            configMapKeyRef:
              name: guidelinesconfigmap
              key: quarantine

        - name: guidelines.liters
          valueFrom:
            configMapKeyRef:
              name: guidelinesconfigmap
              key: liters

        - name: guidelines.temparatureLevels
          valueFrom:
            configMapKeyRef:
              name: guidelinesconfigmap
              key: temparatureLevels

      volumeMounts:
        - name: healthinspectorvolume
          mountPath: /config
          readOnly: true

  volumes:
    - name: healthinspectorvolume
      configMap:
        name: healthinspectorconfigmap
        items:
          - key: district-healthinspectors.properties
            path: district-healthinspector.properties