apiVersion: v1
kind: Pod
metadata:
  name: hangoutpod
  labels:
    appName: hangout
    appVersion: "1.0"
    env: production
  annotations:
    license: Apache GNU License2
    description: hangout application providing travel guide
spec:
  containers:
    - name: hangout
      image: hangout:1.0
      ports:
        - name: hangoutport
          containerPort: 8080
          protocol: TCP